/* 자동 생성 파일 — node tools/manifest.js 로 다시 만든다.
 * img/<사건id>/<키>.(webp|png|jpg) 파일이 있으면 SVG 대신 그 이미지를 쓴다. */
window.MG = window.MG || {};
window.MG.images = {
  "c00/award": "img/c00/award.webp",
  "c00/booth": "img/c00/booth.webp",
  "c00/bridge": "img/c00/bridge.webp",
  "c00/cake": "img/c00/cake.webp",
  "c00/cat": "img/c00/cat.webp",
  "c00/cover": "img/c00/cover.webp",
  "c00/cup": "img/c00/cup.webp",
  "c00/doorbag": "img/c00/doorbag.webp",
  "c00/sketch": "img/c00/sketch.webp",
  "c01/b_register": "img/c01/b_register.webp",
  "c01/cover": "img/c01/cover.webp",
  "c01/l_letter": "img/c01/l_letter.webp",
  "c01/l_postcard": "img/c01/l_postcard.webp",
  "c01/l_slip": "img/c01/l_slip.webp",
  "c01/q_lamp": "img/c01/q_lamp.webp",
  "c01/q_thread": "img/c01/q_thread.webp",
  "c01/s_candle": "img/c01/s_candle.webp",
  "c01/s_court": "img/c01/s_court.webp",
  "c01/s_fundbox": "img/c01/s_fundbox.webp",
  "c01/s_patrol": "img/c01/s_patrol.webp",
  "c01/s_sailor": "img/c01/s_sailor.webp",
  "c01/s_tanners": "img/c01/s_tanners.webp",
  "c02/attic": "img/c02/attic.webp",
  "c02/calendar": "img/c02/calendar.webp",
  "c02/cover": "img/c02/cover.webp",
  "c02/farm": "img/c02/farm.webp",
  "c02/hausbuch": "img/c02/hausbuch.webp",
  "c02/hut": "img/c02/hut.webp",
  "c02/kasten": "img/c02/kasten.webp",
  "c02/kitchen": "img/c02/kitchen.webp",
  "c02/lock": "img/c02/lock.webp",
  "c02/mailbox": "img/c02/mailbox.webp",
  "c02/sledge": "img/c02/sledge.webp",
  "c02/stall": "img/c02/stall.webp",
  "c02/suitcase": "img/c02/suitcase.webp",
  "c03/b_cafe": "img/c03/b_cafe.webp",
  "c03/b_sewing": "img/c03/b_sewing.webp",
  "c03/cover": "img/c03/cover.webp",
  "c03/n_boheol": "img/c03/n_boheol.webp",
  "c03/n_jodk": "img/c03/n_jodk.webp",
  "c03/n_singer": "img/c03/n_singer.webp",
  "c03/p_radio": "img/c03/p_radio.webp",
  "c03/p_safe": "img/c03/p_safe.webp",
  "c03/p_shop": "img/c03/p_shop.webp",
  "c03/p_well": "img/c03/p_well.webp",
  "_global/desk": "img/_global/desk.webp",
  "_global/hero": "img/_global/hero.webp",
  "_global/paper": "img/_global/paper.webp",
  "_global/warn": "img/_global/warn.webp"
};
